import { Lead } from './leadsStore';

export const FALLBACK_BANGALORE_LEADS: Lead[] = [
  {
    id: "fb-1",
    osmId: 101,
    businessName: "Amrutha Condiments & Bakery",
    category: "Bakery & Confectionery",
    location: "17th Cross Rd, Sector 1, HSR Layout, Bengaluru",
    phone: "073497 58370",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/101",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=12.9120415,77.6479898",
    problemDescription: "Custom cake and bakery order requests are handled manually via phone calls and walk-ins, causing order errors during peak hours.",
    pitch: "A digital cake catalog & order customization web app with instant UPI advance payments would automate daily pre-orders.",
    lat: 12.9120415,
    lon: 77.6479898
  },
  {
    id: "fb-2",
    osmId: 102,
    businessName: "Shiro Lounge & Dining",
    category: "Restaurant & Eatery",
    location: "UB City, Vittal Mallya Road, Bengaluru",
    phone: "080 4173 8888",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/102",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=12.9715987,77.5959345",
    problemDescription: "Lacks a direct mobile site for table reservations or digital menu browsing outside walk-in hours.",
    pitch: "A fast online reservation & QR digital menu web app would turn Google search traffic into direct weekend table bookings.",
    lat: 12.9715987,
    lon: 77.5959345
  },
  {
    id: "fb-3",
    osmId: 103,
    businessName: "Hotel Empire",
    category: "Restaurant & Eatery",
    location: "100 Feet Road, Indiranagar, Bengaluru",
    phone: "080 4041 4041",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/103",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=12.9783994,77.6443108",
    problemDescription: "High late-night takeaway queues with zero online pre-order option for direct pickup.",
    pitch: "A direct online pickup & pre-ordering web portal would eliminate counter queues and save 20% commission paid to third-party apps.",
    lat: 12.9783994,
    lon: 77.6443108
  },
  {
    id: "fb-4",
    osmId: 104,
    businessName: "Srujan Dental Care",
    category: "Dental Practice",
    location: "Kalyan Nagar, Bengaluru",
    phone: "080 2545 1122",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/104",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=13.0605539,77.6251495",
    problemDescription: "No online booking portal for dental checkups; missing out on high-intent local search patients in Kalyan Nagar.",
    pitch: "A clean dental booking portal with automated appointment reminders would increase new patient intakes.",
    lat: 13.0605539,
    lon: 77.6251495
  },
  {
    id: "fb-5",
    osmId: 105,
    businessName: "MMA Kababs & Grills",
    category: "Restaurant & Eatery",
    location: "ITPL Main Road, Whitefield, Bengaluru",
    phone: "098860 12345",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/105",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=12.9566296,77.7152069",
    problemDescription: "Relies on manual WhatsApp messages for party catering orders; zero structured menu site.",
    pitch: "A catering menu showcase & online order calculation web app would streamline high-ticket tech park corporate orders.",
    lat: 12.9566296,
    lon: 77.7152069
  },
  {
    id: "fb-6",
    osmId: 106,
    businessName: "Thom's Bakery & Supermarket",
    category: "Bakery & Confectionery",
    location: "Wheeler Road, Frazer Town, Bengaluru",
    phone: "080 2536 1864",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/106",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=12.9915471,77.6141810",
    problemDescription: "Famous Frazer Town bakery with heavy weekend crowds and no online order catalog.",
    pitch: "An online bakery catalog with pre-payment integration would allow customers to order festive specials in advance.",
    lat: 12.9915471,
    lon: 77.6141810
  },
  {
    id: "fb-7",
    osmId: 107,
    businessName: "Simply Native Boutique",
    category: "Boutique & Retail Store",
    location: "Paramahansa Yogananda Road, Indiranagar, Bengaluru",
    phone: "080 4126 5544",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/107",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=12.9651393,77.6383211",
    problemDescription: "New retail arrivals are shared only via Instagram DMs, creating sales bottlenecks.",
    pitch: "A digital product showcase catalog with instant WhatsApp order buttons would boost direct retail sales.",
    lat: 12.9651393,
    lon: 77.6383211
  },
  {
    id: "fb-8",
    osmId: 108,
    businessName: "Koshy's Parade Restaurant",
    category: "Restaurant & Eatery",
    location: "St. Mark's Road, Shanthala Nagar, Bengaluru",
    phone: "080 2221 3793",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/108",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=12.9723000,77.6012000",
    problemDescription: "Iconic Bangalore dining spot with no official digital portal for menu details or table reservations.",
    pitch: "A heritage restaurant showcase site with digital menu integration would preserve tradition while capturing modern diners.",
    lat: 12.9723000,
    lon: 77.6012000
  },
  {
    id: "fb-9",
    osmId: 109,
    businessName: "Lakme Salon Indiranagar",
    category: "Salon & Barber Shop",
    location: "100 Feet Road, Indiranagar, Bengaluru",
    phone: "080 4115 2233",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/109",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=12.9780000,77.6400000",
    problemDescription: "Customers must call or visit in person to check service packages and stylist availability.",
    pitch: "An automated WhatsApp appointment booking assistant & service menu site would let clients schedule appointments 24/7.",
    lat: 12.9780000,
    lon: 77.6400000
  },
  {
    id: "fb-10",
    osmId: 110,
    businessName: "Healing Hands Clinic",
    category: "Medical Clinic",
    location: "17th Cross Road, Sector 1, HSR Layout, Bengaluru",
    phone: "080 4953 8899",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/110",
    gmapsUrl: "https://www.google.com/maps/search/?api=1&query=12.9120415,77.6479898",
    problemDescription: "Patients cannot view doctor schedules or book consultations online, leading to high phone queue friction.",
    pitch: "A doctor schedule site & automated WhatsApp appointment booking assistant would streamline patient check-ins.",
    lat: 12.9120415,
    lon: 77.6479898
  }
];
