import { EnrichedLead } from './types';

export const FALLBACK_HIGH_TICKET_LEADS: EnrichedLead[] = [
  {
    id: "ht-1",
    osmId: 201,
    businessName: "Srujan Dental Care & Polyclinic",
    categoryKey: "dentist",
    categoryDisplay: "DENTIST (Healthcare)",
    targetDomainGroup: "Healthcare & Wellness",
    location: "Kalyan Nagar, Outer Ring Road, Bengaluru",
    phone: "080 2545 1122",
    email: "dr.srujan@dentalcare.in",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/201",
    gmapsUrl: "https://www.google.com/maps/search/Srujan%20Dental%20Care/@13.0605539,77.6251495,17z",
    gmapsPinUrl: "https://maps.google.com/?q=13.0605539,77.6251495",
    qualityScore: 98,
    scoreBreakdown: {
      contactAvailabilityScore: 30,
      categoryValueScore: 40,
      locationMetadataScore: 15,
      brandQualityScore: 13,
      totalScore: 98
    },
    estimatedBudget: "₹45,000 - ₹90,000",
    problemDescription: "No online booking portal for dental checkups; missing out on high-intent local search patients in Kalyan Nagar.",
    pitch: "A clean dental booking portal with automated appointment reminders would increase high-ticket dental patient bookings.",
    lat: 13.0605539,
    lon: 77.6251495
  },
  {
    id: "ht-2",
    osmId: 202,
    businessName: "Oliva Skin & Hair Clinic",
    categoryKey: "clinic",
    categoryDisplay: "CLINIC (Healthcare)",
    targetDomainGroup: "Healthcare & Wellness",
    location: "11th Cross Road, Sector 1, HSR Layout, Bengaluru",
    phone: "1800 103 3800",
    email: "contact@olivaclinic.com",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/202",
    gmapsUrl: "https://www.google.com/maps/search/Oliva%20Skin%20Clinic/@12.9174635,77.6515123,17z",
    gmapsPinUrl: "https://maps.google.com/?q=12.9174635,77.6515123",
    qualityScore: 95,
    scoreBreakdown: {
      contactAvailabilityScore: 30,
      categoryValueScore: 40,
      locationMetadataScore: 15,
      brandQualityScore: 10,
      totalScore: 95
    },
    estimatedBudget: "₹50,000 - ₹1,10,000",
    problemDescription: "Missing a digital skincare consultation booking & laser treatment inquiry portal.",
    pitch: "A cosmetic dermatology consultation booking web app with product trial ordering would convert search traffic into paid client intakes.",
    lat: 12.9174635,
    lon: 77.6515123
  },
  {
    id: "ht-3",
    osmId: 203,
    businessName: "Prestige Property Consultants",
    categoryKey: "estate_agent",
    categoryDisplay: "ESTATE AGENT (B2B)",
    targetDomainGroup: "B2B & Professional",
    location: "Koramangala 4th Block, Bengaluru",
    phone: "080 2559 1080",
    email: "sales@prestigeadvisory.in",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/203",
    gmapsUrl: "https://www.google.com/maps/search/Prestige%20Property/@12.9333646,77.6230728,17z",
    gmapsPinUrl: "https://maps.google.com/?q=12.9333646,77.6230728",
    qualityScore: 95,
    scoreBreakdown: {
      contactAvailabilityScore: 30,
      categoryValueScore: 40,
      locationMetadataScore: 15,
      brandQualityScore: 10,
      totalScore: 95
    },
    estimatedBudget: "₹65,000 - ₹1,80,000",
    problemDescription: "Property buyers cannot browse active villa and apartment listings or schedule site visits online.",
    pitch: "A luxury real estate property web app with interactive floor plans & WhatsApp lead capture would convert HNI buyers.",
    lat: 12.9333646,
    lon: 77.6230728
  },
  {
    id: "ht-4",
    osmId: 204,
    businessName: "Architects Studio & Associates",
    categoryKey: "architect",
    categoryDisplay: "ARCHITECT (B2B)",
    targetDomainGroup: "B2B & Professional",
    location: "100 Feet Road, Indiranagar, Bengaluru",
    phone: "080 4126 9988",
    email: "projects@studioarchitects.in",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/204",
    gmapsUrl: "https://www.google.com/maps/search/Architects%20Studio/@12.9783994,77.6443108,17z",
    gmapsPinUrl: "https://maps.google.com/?q=12.9783994,77.6443108",
    qualityScore: 92,
    scoreBreakdown: {
      contactAvailabilityScore: 30,
      categoryValueScore: 40,
      locationMetadataScore: 12,
      brandQualityScore: 10,
      totalScore: 92
    },
    estimatedBudget: "₹85,000 - ₹2,20,000",
    problemDescription: "Architectural project portfolios are shared via static PDF attachments instead of an interactive digital showcase.",
    pitch: "A high-end architectural portfolio web app with 3D project galleries would capture lucrative residential and commercial clients.",
    lat: 12.9783994,
    lon: 77.6443108
  },
  {
    id: "ht-5",
    osmId: 205,
    businessName: "Prime Auto Workshop & Detailing",
    categoryKey: "car_repair",
    categoryDisplay: "CAR REPAIR (Services)",
    targetDomainGroup: "High-Ticket Local Services",
    location: "ITPL Main Road, Whitefield, Bengaluru",
    phone: "098860 44332",
    email: "service@primeautoworks.in",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/205",
    gmapsUrl: "https://www.google.com/maps/search/Prime%20Auto%20Workshop/@12.9566296,77.7152069,17z",
    gmapsPinUrl: "https://maps.google.com/?q=12.9566296,77.7152069",
    qualityScore: 90,
    scoreBreakdown: {
      contactAvailabilityScore: 30,
      categoryValueScore: 35,
      locationMetadataScore: 15,
      brandQualityScore: 10,
      totalScore: 90
    },
    estimatedBudget: "₹50,000 - ₹1,20,000",
    problemDescription: "Vehicle owners cannot view service price estimates or schedule workshop repair slots digitally.",
    pitch: "An auto repair service estimate calculator & slot booking web app would streamline daily workshop check-ins.",
    lat: 12.9566296,
    lon: 77.7152069
  },
  {
    id: "ht-6",
    osmId: 206,
    businessName: "The Paul Boutique Hotel & Spa",
    categoryKey: "hotel",
    categoryDisplay: "HOTEL (Hospitality)",
    targetDomainGroup: "Hospitality & Venues",
    location: "Domlur, Near Indiranagar, Bengaluru",
    phone: "080 4047 7777",
    email: "reservations@thepaul.in",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/206",
    gmapsUrl: "https://www.google.com/maps/search/The%20Paul%20Hotel/@12.9634000,77.6385000,17z",
    gmapsPinUrl: "https://maps.google.com/?q=12.9634000,77.6385000",
    qualityScore: 90,
    scoreBreakdown: {
      contactAvailabilityScore: 30,
      categoryValueScore: 35,
      locationMetadataScore: 15,
      brandQualityScore: 10,
      totalScore: 90
    },
    estimatedBudget: "₹75,000 - ₹1,90,000",
    problemDescription: "Hotel guests must book via OTAs, costing the hotel 20% in commission fees per room booking.",
    pitch: "A direct hotel booking website with instant UPI payment gateway integration would save thousands in OTA commissions.",
    lat: 12.9634000,
    lon: 77.6385000
  },
  {
    id: "ht-7",
    osmId: 207,
    businessName: "Cult Fit Fitness Centre",
    categoryKey: "fitness_centre",
    categoryDisplay: "FITNESS CENTRE (Services)",
    targetDomainGroup: "High-Ticket Local Services",
    location: "HSR Layout Sector 3, Bengaluru",
    phone: "080 6848 8888",
    email: "info@cultfitcenter.in",
    signal: "No website found",
    osmUrl: "https://www.openstreetmap.org/node/207",
    gmapsUrl: "https://www.google.com/maps/search/Cult%20Fit%20Fitness/@12.9155759,77.6349897,17z",
    gmapsPinUrl: "https://maps.google.com/?q=12.9155759,77.6349897",
    qualityScore: 88,
    scoreBreakdown: {
      contactAvailabilityScore: 25,
      categoryValueScore: 35,
      locationMetadataScore: 15,
      brandQualityScore: 13,
      totalScore: 88
    },
    estimatedBudget: "₹40,000 - ₹85,000",
    problemDescription: "No web portal for trial class signups, workout schedules, or membership pass purchases.",
    pitch: "A trial class booking web app with instant UPI pass payments would convert social media traffic into paid gym members.",
    lat: 12.9155759,
    lon: 77.6349897
  }
];
